[package]
name = "rust-pgdatadiff"
version = "0.1.8"
license = "MIT"
edition = "2024"
description = "Rust library for comparing two PostgreSQL databases"
readme = "README.md"
homepage = "https://github.com/pavlospt/rust-pgdatadiff"
repository = "https://github.com/pavlospt/rust-pgdatadiff"
keywords = ["postgres", "postgresql", "diff"]
documentation = "https://docs.rs/rust-pgdatadiff"

[workspace]
members = ["rust-pgdatadiff-client"]

[workspace.dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
colored = "3"
futures = { version = "0.3", default-features = true, features = [
    "async-await",
] }
async-trait = "0.1"
pretty_assertions = "1"
mockall = "0.13"
tracing-subscriber = "0.3"
tracing = "0.1"
deadpool-postgres = "0.14"
postgres-native-tls = "0.5"
native-tls = "0.2"
clap = { version = "4", features = ["derive"] }
rust-pgdatadiff = { path = ".", version = "0.1.8" }

[dependencies]
anyhow.workspace = true
tokio.workspace = true
colored.workspace = true
futures.workspace = true
async-trait.workspace = true
pretty_assertions.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
deadpool-postgres.workspace = true
postgres-native-tls.workspace = true
native-tls.workspace = true

[dev-dependencies]
mockall.workspace = true
tokio.workspace = true
clap.workspace = true
testcontainers = { version = "0.27", features = ["http_wait"] }

[lib]
test = true
crate-type = ["lib"]
name = "rust_pgdatadiff"
