name: OSV Scan

on: push

jobs:
  vuln-scan:
    name: Vulnerability scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1.9.2
        with:
          scan-args: |-
            --lockfile=Cargo.lock
        continue-on-error: true
